Workaround rustc issue for panic=abort and unwrap
Would produle linker error similar to:
 /usr/bin/ld: …: in function `core::result::unwrap_failed':
 /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/result.rs:998: undefined reference to `_Unwind_Resume'

Possibly some reference to the raw unwinding functions that are not
omitted since they are guarded by `if` instead of feature flags (rust
std library is one binary, not one per feature combination of course).