Basic XDP program lookup
We don't check the BTF (description file) yet so this has some false
positives. However, the setup in general is somewhat okay.

Weirdly, I seem to get miscompilations with the intended break-on-legacy
path that emulates the respective C goto! If I _don't_ print in the
check then the program returns with

	# ../target/x86_64-unknown-linux-gnu/debug/examples/iperf3 loop0 127.0.0.1/24 aa:1b:68:c8:0c:b7 127.0.0.2/24 -c 127.0.0.2 80  -l 1000 -n 1000 --tcp
	thread 'main' panicked at 'Failed to create interface: AfXdpBuilderError { _inner: BadProgConfigMap }', ethox-afxdp/examples/iperf3.rs:38:6
	note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

The diff is literally:

 	if prog_info.btf_id == 0 {
-	    eprint!("{}", "Huh?\n");
 	    return Err(AttachError::NoLegacySupport);
 	}

Without this diff everything works as expected:

	# ../target/x86_64-unknown-linux-gnu/debug/examples/iperf3 loop0 127.0.0.1/24 aa:1b:68:c8:0c:b7 127.0.0.2/24 -c 127.0.0.2 80  -l 1000 -n 1000 --tcp
	BpfMapInfo { type_: 2, id: 14, key_size: 4, value_size: 84, max_entries: 1, map_flags: 1152, name: [120, 100, 112, 95, 100, 105, 115, 112, 46, 114, 111, 100, 97, 116, 97, 0], ifindex: 0, btf_vmlinux_value_type_id: 0, netns_dev: 0, netns_ino: 0, btf_id: 178, btf_key_type_id: 0, btf_value_type_id: 46, _pad: 0, map_extra: 0 }
	84
	(4, 84)
	(Some(4), Some(84))
	thread 'main' panicked at 'not yet implemented', ethox-afxdp/src/xdp.rs:247:9

Note that the print doesn't show up, it's dead code unless it's missing. What?